/**
 * Data Export Utilities for Admin Panel
 * Export audit logs, transactions, users to CSV/JSON
 */

import type { AuditLogEntry, SuspiciousActivityFlag } from "./admin-storage";
import type { TransactionModel } from "@/components/data/orm/orm_transaction";
import type { UserModel } from "@/components/data/orm/orm_user";

export function exportToCSV(data: unknown[], filename: string): void {
  if (data.length === 0) {
    throw new Error("No data to export");
  }

  // Get all unique keys from data
  const allKeys = new Set<string>();
  data.forEach((item) => {
    if (typeof item === "object" && item !== null) {
      Object.keys(item).forEach((key) => allKeys.add(key));
    }
  });

  const headers = Array.from(allKeys);
  const csvRows = [headers.join(",")];

  // Convert each row to CSV
  data.forEach((item) => {
    if (typeof item === "object" && item !== null) {
      const values = headers.map((header) => {
        const value = (item as Record<string, unknown>)[header];
        if (value === null || value === undefined) return "";

        // Escape quotes and wrap in quotes if contains comma/newline
        const stringValue = String(value);
        if (stringValue.includes(",") || stringValue.includes("\n") || stringValue.includes('"')) {
          return `"${stringValue.replace(/"/g, '""')}"`;
        }
        return stringValue;
      });
      csvRows.push(values.join(","));
    }
  });

  const csvContent = csvRows.join("\n");
  downloadFile(csvContent, filename, "text/csv");
}

export function exportToJSON(data: unknown[], filename: string): void {
  const jsonContent = JSON.stringify(data, null, 2);
  downloadFile(jsonContent, filename, "application/json");
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAuditLogs(logs: AuditLogEntry[], format: "csv" | "json" = "csv"): void {
  const filename = `audit-logs-${new Date().toISOString().split("T")[0]}.${format}`;

  if (format === "csv") {
    exportToCSV(logs, filename);
  } else {
    exportToJSON(logs, filename);
  }
}

export function exportTransactions(transactions: TransactionModel[], format: "csv" | "json" = "csv"): void {
  const filename = `transactions-${new Date().toISOString().split("T")[0]}.${format}`;

  if (format === "csv") {
    exportToCSV(transactions, filename);
  } else {
    exportToJSON(transactions, filename);
  }
}

export function exportUsers(users: UserModel[], format: "csv" | "json" = "csv"): void {
  // Remove sensitive data before export
  const sanitizedUsers = users.map((user) => ({
    id: user.id,
    email: user.email,
    full_name: user.full_name,
    create_time: user.create_time,
    update_time: user.update_time,
    theme_preference: user.theme_preference,
  }));

  const filename = `users-${new Date().toISOString().split("T")[0]}.${format}`;

  if (format === "csv") {
    exportToCSV(sanitizedUsers, filename);
  } else {
    exportToJSON(sanitizedUsers, filename);
  }
}

export function exportSuspiciousActivity(flags: SuspiciousActivityFlag[], format: "csv" | "json" = "csv"): void {
  const filename = `suspicious-activity-${new Date().toISOString().split("T")[0]}.${format}`;

  if (format === "csv") {
    exportToCSV(flags, filename);
  } else {
    exportToJSON(flags, filename);
  }
}

export function generateSystemReport(): string {
  const report = {
    generatedAt: new Date().toISOString(),
    systemStatus: JSON.parse(localStorage.getItem("banking_system_status") || "{}"),
    auditLogCount: (JSON.parse(localStorage.getItem("banking_audit_log") || "[]") as unknown[]).length,
    suspiciousActivityCount: (JSON.parse(localStorage.getItem("banking_suspicious_activity") || "[]") as unknown[]).length,
    adminUserCount: (JSON.parse(localStorage.getItem("banking_admin_users") || "[]") as unknown[]).length,
  };

  const reportContent = `
# SecureBank System Report
Generated: ${report.generatedAt}

## System Status
${JSON.stringify(report.systemStatus, null, 2)}

## Statistics
- Total Audit Logs: ${report.auditLogCount}
- Suspicious Activities: ${report.suspiciousActivityCount}
- Admin Users: ${report.adminUserCount}

---
This is an automated system report generated by SecureBank Admin Console.
`;

  return reportContent;
}

export function downloadSystemReport(): void {
  const content = generateSystemReport();
  const filename = `system-report-${new Date().toISOString().split("T")[0]}.md`;
  downloadFile(content, filename, "text/markdown");
}
