// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: kyc_verification.
// - Entity ID: 102019b1c43eac8710f9a121341d8a777d1.
// - Entity Version: 102019b3612e2f0746cb43826627dd52e1d.
// - Task ID: 6945235f40179249e0d105dc.
// - Task Root ID: 693be70dec184ca07e4e3fe1.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for KycVerificationDocumentType
 */
export enum KycVerificationDocumentType {
  Unspecified = 0,
}
/**
 * Enumeration for KycVerificationVerificationStatus
 */
export enum KycVerificationVerificationStatus {
  Unspecified = 0,
}



/**
 * Interface for KycVerificationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface KycVerificationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  document_type: KycVerificationDocumentType;
  document_number: string;
  document_url: string;
  verification_status: KycVerificationVerificationStatus;
  rejection_reason?: string | null;
}

/**
 * ORM class for KycVerification entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class KycVerificationORM {
  private static instance: KycVerificationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1c43eac8710f9a121341d8a777d1';
    this.entityName = 'kyc_verification';
    this.entityVersion = '102019b3612e2f0746cb43826627dd52e1d';
    this.taskId = '6945235f40179249e0d105dc';
    this.taskRootId = '693be70dec184ca07e4e3fe1';
  }

  /**
   * Get singleton instance of KycVerificationORM
   */
  public static getInstance(): KycVerificationORM {
    if (!KycVerificationORM.instance) {
      KycVerificationORM.instance = new KycVerificationORM();
    }
    
    return KycVerificationORM.instance;
  }

  /**
   * Get kyc_verification by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getKycVerificationByIDs(ids: string[]): Promise<KycVerificationModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete kyc_verification by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteKycVerificationByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all KycVerification records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllKycVerification(): Promise<KycVerificationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new KycVerification record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertKycVerification(data: KycVerificationModel[]): Promise<KycVerificationModel[]> {
    const structured = data.map((item) => CreateData(KycVerificationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all KycVerification records
   */
  async purgeAllKycVerification(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List KycVerification records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listKycVerification(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[KycVerificationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get kyc_verification by Id index
   * This function gets data by index.
   */
  async getKycVerificationById(
    id: string,
  ): Promise<KycVerificationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) kyc_verification by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKycVerificationById(
    id: string,
    data: KycVerificationModel
  ): Promise<KycVerificationModel[]> {
    const index = createIndexId(
      id
    );

    const values = KycVerificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete kyc_verification by Id index
   */
  async deleteKycVerificationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get kyc_verification by UserId index
   * This function gets data by index.
   */
  async getKycVerificationByUserId(
    user_id: string,
  ): Promise<KycVerificationModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) kyc_verification by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKycVerificationByUserId(
    user_id: string,
    data: KycVerificationModel
  ): Promise<KycVerificationModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = KycVerificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete kyc_verification by UserId index
   */
  async deleteKycVerificationByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get kyc_verification by VerificationStatus index
   * This function gets data by index.
   */
  async getKycVerificationByVerificationStatus(
    verification_status: KycVerificationVerificationStatus,
  ): Promise<KycVerificationModel[]> {
    const index = createIndexVerificationStatus(
      verification_status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) kyc_verification by VerificationStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKycVerificationByVerificationStatus(
    verification_status: KycVerificationVerificationStatus,
    data: KycVerificationModel
  ): Promise<KycVerificationModel[]> {
    const index = createIndexVerificationStatus(
      verification_status
    );

    const values = KycVerificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete kyc_verification by VerificationStatus index
   */
  async deleteKycVerificationByVerificationStatus(
    verification_status: KycVerificationVerificationStatus
  ): Promise<void> {
    const index = createIndexVerificationStatus(
      verification_status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get kyc_verification by DataCreator index
   * This function gets data by index.
   */
  async getKycVerificationByDataCreator(
    data_creator: string,
  ): Promise<KycVerificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) kyc_verification by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKycVerificationByDataCreator(
    data_creator: string,
    data: KycVerificationModel
  ): Promise<KycVerificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = KycVerificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete kyc_verification by DataCreator index
   */
  async deleteKycVerificationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get kyc_verification by DataUpdater index
   * This function gets data by index.
   */
  async getKycVerificationByDataUpdater(
    data_updater: string,
  ): Promise<KycVerificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) kyc_verification by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKycVerificationByDataUpdater(
    data_updater: string,
    data: KycVerificationModel
  ): Promise<KycVerificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = KycVerificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete kyc_verification by DataUpdater index
   */
  async deleteKycVerificationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to KycVerificationModel data array
   */
  private resultToData(values: Data[]): KycVerificationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return KycVerificationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as KycVerificationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized KycVerificationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is KycVerificationModel => item !== null);
  }
}

/**
 * Convert KycVerificationModel data to Value array
 */
function KycVerificationModelToValues(data: KycVerificationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'document_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'document_number', type: DataType.string, defaultValue: '' },
    { key: 'document_url', type: DataType.string, defaultValue: '' },
    { key: 'verification_status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'rejection_reason', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof KycVerificationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to KycVerificationModel data
 */
function KycVerificationModelFromValues(values: Value[]): KycVerificationModel {
  const data: Partial<KycVerificationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'document_type':
        data.document_type = ParseValue(value, DataType.enumeration) as KycVerificationDocumentType;
        break;
      case 'document_number':
        data.document_number = ParseValue(value, DataType.string) as string;
        break;
      case 'document_url':
        data.document_url = ParseValue(value, DataType.string) as string;
        break;
      case 'verification_status':
        data.verification_status = ParseValue(value, DataType.enumeration) as KycVerificationVerificationStatus;
        break;
      case 'rejection_reason':
        data.rejection_reason = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as KycVerificationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for VerificationStatus fields
 */
function createIndexVerificationStatus(
  verification_status: KycVerificationVerificationStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, verification_status, 'verification_status'),
  ];

  return {
    fields: ['verification_status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default KycVerificationORM;