// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: suspicious_activity.
// - Entity ID: 102019b1c43eac878acb4e236f5a0e09869.
// - Entity Version: 102019b3612e2f0746cb43826627dd52e1d.
// - Task ID: 6945235f40179249e0d105dc.
// - Task Root ID: 693be70dec184ca07e4e3fe1.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for SuspiciousActivitySeverity
 */
export enum SuspiciousActivitySeverity {
  Unspecified = 0,
}
/**
 * Enumeration for SuspiciousActivityStatus
 */
export enum SuspiciousActivityStatus {
  Unspecified = 0,
}



/**
 * Interface for SuspiciousActivityModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SuspiciousActivityModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  target_entity: string;
  target_id: string;
  reason: string;
  severity: SuspiciousActivitySeverity;
  status: SuspiciousActivityStatus;
}

/**
 * ORM class for SuspiciousActivity entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SuspiciousActivityORM {
  private static instance: SuspiciousActivityORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1c43eac878acb4e236f5a0e09869';
    this.entityName = 'suspicious_activity';
    this.entityVersion = '102019b3612e2f0746cb43826627dd52e1d';
    this.taskId = '6945235f40179249e0d105dc';
    this.taskRootId = '693be70dec184ca07e4e3fe1';
  }

  /**
   * Get singleton instance of SuspiciousActivityORM
   */
  public static getInstance(): SuspiciousActivityORM {
    if (!SuspiciousActivityORM.instance) {
      SuspiciousActivityORM.instance = new SuspiciousActivityORM();
    }
    
    return SuspiciousActivityORM.instance;
  }

  /**
   * Get suspicious_activity by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getSuspiciousActivityByIDs(ids: string[]): Promise<SuspiciousActivityModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteSuspiciousActivityByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all SuspiciousActivity records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSuspiciousActivity(): Promise<SuspiciousActivityModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SuspiciousActivity record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSuspiciousActivity(data: SuspiciousActivityModel[]): Promise<SuspiciousActivityModel[]> {
    const structured = data.map((item) => CreateData(SuspiciousActivityModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SuspiciousActivity records
   */
  async purgeAllSuspiciousActivity(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SuspiciousActivity records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSuspiciousActivity(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SuspiciousActivityModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get suspicious_activity by Id index
   * This function gets data by index.
   */
  async getSuspiciousActivityById(
    id: string,
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) suspicious_activity by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSuspiciousActivityById(
    id: string,
    data: SuspiciousActivityModel
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexId(
      id
    );

    const values = SuspiciousActivityModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by Id index
   */
  async deleteSuspiciousActivityById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get suspicious_activity by TargetEntityTargetId index
   * This function gets data by index.
   */
  async getSuspiciousActivityByTargetEntityTargetId(
    target_entity: string,
    target_id: string,
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexTargetEntityTargetId(
      target_entity,
      target_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) suspicious_activity by TargetEntityTargetId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSuspiciousActivityByTargetEntityTargetId(
    target_entity: string,
    target_id: string,
    data: SuspiciousActivityModel
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexTargetEntityTargetId(
      target_entity,
      target_id
    );

    const values = SuspiciousActivityModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by TargetEntityTargetId index
   */
  async deleteSuspiciousActivityByTargetEntityTargetId(
    target_entity: string,
    target_id: string
  ): Promise<void> {
    const index = createIndexTargetEntityTargetId(
      target_entity,
      target_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get suspicious_activity by Status index
   * This function gets data by index.
   */
  async getSuspiciousActivityByStatus(
    status: SuspiciousActivityStatus,
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) suspicious_activity by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSuspiciousActivityByStatus(
    status: SuspiciousActivityStatus,
    data: SuspiciousActivityModel
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = SuspiciousActivityModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by Status index
   */
  async deleteSuspiciousActivityByStatus(
    status: SuspiciousActivityStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get suspicious_activity by Severity index
   * This function gets data by index.
   */
  async getSuspiciousActivityBySeverity(
    severity: SuspiciousActivitySeverity,
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexSeverity(
      severity
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) suspicious_activity by Severity index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSuspiciousActivityBySeverity(
    severity: SuspiciousActivitySeverity,
    data: SuspiciousActivityModel
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexSeverity(
      severity
    );

    const values = SuspiciousActivityModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by Severity index
   */
  async deleteSuspiciousActivityBySeverity(
    severity: SuspiciousActivitySeverity
  ): Promise<void> {
    const index = createIndexSeverity(
      severity
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get suspicious_activity by DataCreator index
   * This function gets data by index.
   */
  async getSuspiciousActivityByDataCreator(
    data_creator: string,
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) suspicious_activity by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSuspiciousActivityByDataCreator(
    data_creator: string,
    data: SuspiciousActivityModel
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SuspiciousActivityModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by DataCreator index
   */
  async deleteSuspiciousActivityByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get suspicious_activity by DataUpdater index
   * This function gets data by index.
   */
  async getSuspiciousActivityByDataUpdater(
    data_updater: string,
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) suspicious_activity by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSuspiciousActivityByDataUpdater(
    data_updater: string,
    data: SuspiciousActivityModel
  ): Promise<SuspiciousActivityModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SuspiciousActivityModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete suspicious_activity by DataUpdater index
   */
  async deleteSuspiciousActivityByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SuspiciousActivityModel data array
   */
  private resultToData(values: Data[]): SuspiciousActivityModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SuspiciousActivityModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SuspiciousActivityModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SuspiciousActivityModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SuspiciousActivityModel => item !== null);
  }
}

/**
 * Convert SuspiciousActivityModel data to Value array
 */
function SuspiciousActivityModelToValues(data: SuspiciousActivityModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'target_entity', type: DataType.string, defaultValue: '' },
    { key: 'target_id', type: DataType.string, defaultValue: '' },
    { key: 'reason', type: DataType.string, defaultValue: '' },
    { key: 'severity', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SuspiciousActivityModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SuspiciousActivityModel data
 */
function SuspiciousActivityModelFromValues(values: Value[]): SuspiciousActivityModel {
  const data: Partial<SuspiciousActivityModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'target_entity':
        data.target_entity = ParseValue(value, DataType.string) as string;
        break;
      case 'target_id':
        data.target_id = ParseValue(value, DataType.string) as string;
        break;
      case 'reason':
        data.reason = ParseValue(value, DataType.string) as string;
        break;
      case 'severity':
        data.severity = ParseValue(value, DataType.enumeration) as SuspiciousActivitySeverity;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as SuspiciousActivityStatus;
        break;
    }
  }
  
  return data as SuspiciousActivityModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for TargetEntityTargetId fields
 */
function createIndexTargetEntityTargetId(
  target_entity: string,
  target_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, target_entity, 'target_entity'),
    CreateValue(DataType.string, target_id, 'target_id'),
  ];

  return {
    fields: ['target_entity', 'target_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: SuspiciousActivityStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for Severity fields
 */
function createIndexSeverity(
  severity: SuspiciousActivitySeverity
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, severity, 'severity'),
  ];

  return {
    fields: ['severity'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SuspiciousActivityORM;