// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: login_attempt.
// - Entity ID: 102019b1c43eac87ba9b4e0d0c81b892013.
// - Entity Version: 102019b3612e2f0746cb43826627dd52e1d.
// - Task ID: 6945235f40179249e0d105dc.
// - Task Root ID: 693be70dec184ca07e4e3fe1.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for LoginAttemptModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface LoginAttemptModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  email: string;
  ip_address: string;
  success: boolean;
  failure_reason?: string | null;
  user_agent?: string | null;
}

/**
 * ORM class for LoginAttempt entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class LoginAttemptORM {
  private static instance: LoginAttemptORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1c43eac87ba9b4e0d0c81b892013';
    this.entityName = 'login_attempt';
    this.entityVersion = '102019b3612e2f0746cb43826627dd52e1d';
    this.taskId = '6945235f40179249e0d105dc';
    this.taskRootId = '693be70dec184ca07e4e3fe1';
  }

  /**
   * Get singleton instance of LoginAttemptORM
   */
  public static getInstance(): LoginAttemptORM {
    if (!LoginAttemptORM.instance) {
      LoginAttemptORM.instance = new LoginAttemptORM();
    }
    
    return LoginAttemptORM.instance;
  }

  /**
   * Get login_attempt by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getLoginAttemptByIDs(ids: string[]): Promise<LoginAttemptModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteLoginAttemptByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all LoginAttempt records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllLoginAttempt(): Promise<LoginAttemptModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new LoginAttempt record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertLoginAttempt(data: LoginAttemptModel[]): Promise<LoginAttemptModel[]> {
    const structured = data.map((item) => CreateData(LoginAttemptModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all LoginAttempt records
   */
  async purgeAllLoginAttempt(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List LoginAttempt records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listLoginAttempt(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[LoginAttemptModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get login_attempt by Id index
   * This function gets data by index.
   */
  async getLoginAttemptById(
    id: string,
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) login_attempt by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLoginAttemptById(
    id: string,
    data: LoginAttemptModel
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexId(
      id
    );

    const values = LoginAttemptModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by Id index
   */
  async deleteLoginAttemptById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get login_attempt by Email index
   * This function gets data by index.
   */
  async getLoginAttemptByEmail(
    email: string,
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) login_attempt by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLoginAttemptByEmail(
    email: string,
    data: LoginAttemptModel
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = LoginAttemptModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by Email index
   */
  async deleteLoginAttemptByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get login_attempt by IpAddress index
   * This function gets data by index.
   */
  async getLoginAttemptByIpAddress(
    ip_address: string,
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexIpAddress(
      ip_address
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) login_attempt by IpAddress index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLoginAttemptByIpAddress(
    ip_address: string,
    data: LoginAttemptModel
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexIpAddress(
      ip_address
    );

    const values = LoginAttemptModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by IpAddress index
   */
  async deleteLoginAttemptByIpAddress(
    ip_address: string
  ): Promise<void> {
    const index = createIndexIpAddress(
      ip_address
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get login_attempt by CreateTime index
   * This function gets data by index.
   */
  async getLoginAttemptByCreateTime(
    create_time: string,
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) login_attempt by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLoginAttemptByCreateTime(
    create_time: string,
    data: LoginAttemptModel
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = LoginAttemptModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by CreateTime index
   */
  async deleteLoginAttemptByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get login_attempt by DataCreator index
   * This function gets data by index.
   */
  async getLoginAttemptByDataCreator(
    data_creator: string,
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) login_attempt by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLoginAttemptByDataCreator(
    data_creator: string,
    data: LoginAttemptModel
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = LoginAttemptModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by DataCreator index
   */
  async deleteLoginAttemptByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get login_attempt by DataUpdater index
   * This function gets data by index.
   */
  async getLoginAttemptByDataUpdater(
    data_updater: string,
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) login_attempt by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLoginAttemptByDataUpdater(
    data_updater: string,
    data: LoginAttemptModel
  ): Promise<LoginAttemptModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = LoginAttemptModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete login_attempt by DataUpdater index
   */
  async deleteLoginAttemptByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to LoginAttemptModel data array
   */
  private resultToData(values: Data[]): LoginAttemptModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return LoginAttemptModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as LoginAttemptModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized LoginAttemptModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is LoginAttemptModel => item !== null);
  }
}

/**
 * Convert LoginAttemptModel data to Value array
 */
function LoginAttemptModelToValues(data: LoginAttemptModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'ip_address', type: DataType.string, defaultValue: '' },
    { key: 'success', type: DataType.boolean, defaultValue: false },
    { key: 'failure_reason', type: DataType.string, defaultValue: null },
    { key: 'user_agent', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof LoginAttemptModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to LoginAttemptModel data
 */
function LoginAttemptModelFromValues(values: Value[]): LoginAttemptModel {
  const data: Partial<LoginAttemptModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'ip_address':
        data.ip_address = ParseValue(value, DataType.string) as string;
        break;
      case 'success':
        data.success = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'failure_reason':
        data.failure_reason = ParseValue(value, DataType.string) as string | null;
        break;
      case 'user_agent':
        data.user_agent = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as LoginAttemptModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for IpAddress fields
 */
function createIndexIpAddress(
  ip_address: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, ip_address, 'ip_address'),
  ];

  return {
    fields: ['ip_address'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default LoginAttemptORM;