/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminConsoleRouteImport } from './routes/admin-console'
import { Route as AccountTypeRouteImport } from './routes/account-type'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingIndexRouteImport } from './routes/marketing/index'
import { Route as MarketingSecurityRouteImport } from './routes/marketing/security'
import { Route as MarketingPricingRouteImport } from './routes/marketing/pricing'
import { Route as MarketingHowItWorksRouteImport } from './routes/marketing/how-it-works'
import { Route as MarketingFeaturesRouteImport } from './routes/marketing/features'
import { Route as MarketingAboutRouteImport } from './routes/marketing/about'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin-console',
  path: '/admin-console',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTypeRoute = AccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSecurityRoute = MarketingSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHowItWorksRoute = MarketingHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/signup': typeof SignupRoute
  '/marketing/about': typeof MarketingAboutRoute
  '/marketing/features': typeof MarketingFeaturesRoute
  '/marketing/how-it-works': typeof MarketingHowItWorksRoute
  '/marketing/pricing': typeof MarketingPricingRoute
  '/marketing/security': typeof MarketingSecurityRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/marketing/about': typeof MarketingAboutRoute
  '/marketing/features': typeof MarketingFeaturesRoute
  '/marketing/how-it-works': typeof MarketingHowItWorksRoute
  '/marketing/pricing': typeof MarketingPricingRoute
  '/marketing/security': typeof MarketingSecurityRoute
  '/marketing': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/signup': typeof SignupRoute
  '/marketing/about': typeof MarketingAboutRoute
  '/marketing/features': typeof MarketingFeaturesRoute
  '/marketing/how-it-works': typeof MarketingHowItWorksRoute
  '/marketing/pricing': typeof MarketingPricingRoute
  '/marketing/security': typeof MarketingSecurityRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-type'
    | '/admin-console'
    | '/dashboard'
    | '/login'
    | '/marketing'
    | '/signup'
    | '/marketing/about'
    | '/marketing/features'
    | '/marketing/how-it-works'
    | '/marketing/pricing'
    | '/marketing/security'
    | '/marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-type'
    | '/admin-console'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/marketing/about'
    | '/marketing/features'
    | '/marketing/how-it-works'
    | '/marketing/pricing'
    | '/marketing/security'
    | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/account-type'
    | '/admin-console'
    | '/dashboard'
    | '/login'
    | '/marketing'
    | '/signup'
    | '/marketing/about'
    | '/marketing/features'
    | '/marketing/how-it-works'
    | '/marketing/pricing'
    | '/marketing/security'
    | '/marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountTypeRoute: typeof AccountTypeRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-console': {
      id: '/admin-console'
      path: '/admin-console'
      fullPath: '/admin-console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-type': {
      id: '/account-type'
      path: '/account-type'
      fullPath: '/account-type'
      preLoaderRoute: typeof AccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/security': {
      id: '/marketing/security'
      path: '/security'
      fullPath: '/marketing/security'
      preLoaderRoute: typeof MarketingSecurityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/pricing': {
      id: '/marketing/pricing'
      path: '/pricing'
      fullPath: '/marketing/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/how-it-works': {
      id: '/marketing/how-it-works'
      path: '/how-it-works'
      fullPath: '/marketing/how-it-works'
      preLoaderRoute: typeof MarketingHowItWorksRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/features': {
      id: '/marketing/features'
      path: '/features'
      fullPath: '/marketing/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/about': {
      id: '/marketing/about'
      path: '/about'
      fullPath: '/marketing/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingHowItWorksRoute: typeof MarketingHowItWorksRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingSecurityRoute: typeof MarketingSecurityRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingHowItWorksRoute: MarketingHowItWorksRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingSecurityRoute: MarketingSecurityRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountTypeRoute: AccountTypeRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
