/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MarketingImport } from './routes/marketing'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AdminConsoleImport } from './routes/admin-console'
import { Route as IndexImport } from './routes/index'
import { Route as MarketingIndexImport } from './routes/marketing/index'
import { Route as MarketingSecurityImport } from './routes/marketing/security'
import { Route as MarketingPricingImport } from './routes/marketing/pricing'
import { Route as MarketingHowItWorksImport } from './routes/marketing/how-it-works'
import { Route as MarketingFeaturesImport } from './routes/marketing/features'
import { Route as MarketingAboutImport } from './routes/marketing/about'

// Create/Update Routes

const MarketingRoute = MarketingImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminConsoleRoute = AdminConsoleImport.update({
  id: '/admin-console',
  path: '/admin-console',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MarketingIndexRoute = MarketingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)

const MarketingSecurityRoute = MarketingSecurityImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MarketingRoute,
} as any)

const MarketingPricingRoute = MarketingPricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)

const MarketingHowItWorksRoute = MarketingHowItWorksImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => MarketingRoute,
} as any)

const MarketingFeaturesRoute = MarketingFeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)

const MarketingAboutRoute = MarketingAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-console': {
      id: '/admin-console'
      path: '/admin-console'
      fullPath: '/admin-console'
      preLoaderRoute: typeof AdminConsoleImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingImport
      parentRoute: typeof rootRoute
    }
    '/marketing/about': {
      id: '/marketing/about'
      path: '/about'
      fullPath: '/marketing/about'
      preLoaderRoute: typeof MarketingAboutImport
      parentRoute: typeof MarketingImport
    }
    '/marketing/features': {
      id: '/marketing/features'
      path: '/features'
      fullPath: '/marketing/features'
      preLoaderRoute: typeof MarketingFeaturesImport
      parentRoute: typeof MarketingImport
    }
    '/marketing/how-it-works': {
      id: '/marketing/how-it-works'
      path: '/how-it-works'
      fullPath: '/marketing/how-it-works'
      preLoaderRoute: typeof MarketingHowItWorksImport
      parentRoute: typeof MarketingImport
    }
    '/marketing/pricing': {
      id: '/marketing/pricing'
      path: '/pricing'
      fullPath: '/marketing/pricing'
      preLoaderRoute: typeof MarketingPricingImport
      parentRoute: typeof MarketingImport
    }
    '/marketing/security': {
      id: '/marketing/security'
      path: '/security'
      fullPath: '/marketing/security'
      preLoaderRoute: typeof MarketingSecurityImport
      parentRoute: typeof MarketingImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexImport
      parentRoute: typeof MarketingImport
    }
  }
}

// Create and export the route tree

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingHowItWorksRoute: typeof MarketingHowItWorksRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingSecurityRoute: typeof MarketingSecurityRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingHowItWorksRoute: MarketingHowItWorksRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingSecurityRoute: MarketingSecurityRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/marketing/about': typeof MarketingAboutRoute
  '/marketing/features': typeof MarketingFeaturesRoute
  '/marketing/how-it-works': typeof MarketingHowItWorksRoute
  '/marketing/pricing': typeof MarketingPricingRoute
  '/marketing/security': typeof MarketingSecurityRoute
  '/marketing/': typeof MarketingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/marketing/about': typeof MarketingAboutRoute
  '/marketing/features': typeof MarketingFeaturesRoute
  '/marketing/how-it-works': typeof MarketingHowItWorksRoute
  '/marketing/pricing': typeof MarketingPricingRoute
  '/marketing/security': typeof MarketingSecurityRoute
  '/marketing': typeof MarketingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/marketing/about': typeof MarketingAboutRoute
  '/marketing/features': typeof MarketingFeaturesRoute
  '/marketing/how-it-works': typeof MarketingHowItWorksRoute
  '/marketing/pricing': typeof MarketingPricingRoute
  '/marketing/security': typeof MarketingSecurityRoute
  '/marketing/': typeof MarketingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-console'
    | '/dashboard'
    | '/marketing'
    | '/marketing/about'
    | '/marketing/features'
    | '/marketing/how-it-works'
    | '/marketing/pricing'
    | '/marketing/security'
    | '/marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-console'
    | '/dashboard'
    | '/marketing/about'
    | '/marketing/features'
    | '/marketing/how-it-works'
    | '/marketing/pricing'
    | '/marketing/security'
    | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/admin-console'
    | '/dashboard'
    | '/marketing'
    | '/marketing/about'
    | '/marketing/features'
    | '/marketing/how-it-works'
    | '/marketing/pricing'
    | '/marketing/security'
    | '/marketing/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  DashboardRoute: typeof DashboardRoute
  MarketingRoute: typeof MarketingRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  DashboardRoute: DashboardRoute,
  MarketingRoute: MarketingRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin-console",
        "/dashboard",
        "/marketing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin-console": {
      "filePath": "admin-console.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/marketing": {
      "filePath": "marketing.tsx",
      "children": [
        "/marketing/about",
        "/marketing/features",
        "/marketing/how-it-works",
        "/marketing/pricing",
        "/marketing/security",
        "/marketing/"
      ]
    },
    "/marketing/about": {
      "filePath": "marketing/about.tsx",
      "parent": "/marketing"
    },
    "/marketing/features": {
      "filePath": "marketing/features.tsx",
      "parent": "/marketing"
    },
    "/marketing/how-it-works": {
      "filePath": "marketing/how-it-works.tsx",
      "parent": "/marketing"
    },
    "/marketing/pricing": {
      "filePath": "marketing/pricing.tsx",
      "parent": "/marketing"
    },
    "/marketing/security": {
      "filePath": "marketing/security.tsx",
      "parent": "/marketing"
    },
    "/marketing/": {
      "filePath": "marketing/index.tsx",
      "parent": "/marketing"
    }
  }
}
ROUTE_MANIFEST_END */
